#https://iamscum.wordpress.com/guides/videoplayback-guide/mpv-conf/

profile=dplii
ytdl-format="(bestvideo[vcodec!~='av01'][height=2160]/bestvideo[height<2160])+bestaudio"

# https://github.com/mpv-player/mpv/issues/2214
[dplii]
profile-desc="downmix 5.1 surround to Dolby Pro Logic II compatible stereo"
# mpv's own pan filter, obsolete
#af=pan=2:[1,0,0,1,0.7071,0.7071,1,1,-0.8718,0.4899,-0.4899,0.8718]
# lavrresample method, should be drop-in replacement for the above:
#af='pan="stereo| FL = FL + 0.7071*FC + LFE + -0.7071*BL + -0.7071*BR | FR = FR + 0.7071*FC + LFE + 0.7071*BL + 0.7071*BR"'
# same as above, and normalizing audio to avoid clipping (shouldn't be necessary for movies)
#af='pan=stereo| FL < FL + 0.7071*FC + LFE + -0.7071*BL + -0.7071*SR | FR < FR + 0.7071*FC + LFE + 0.7071*SL + 0.7071*BR'
# swresample method, use that unless you want to tweak the balance manually:
audio-swresample-o=matrix_encoding=dplii,lfe_mix_level=1
audio-channels=stereo

