windowrule = opacity 0.85, match:class (kitty)
windowrule = opacity 0.85, match:class (dolphin)
windowrule = opacity 0.9, match:class (Spotify)

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

windowrule = suppress_event maximize, match:class .*


windowrule = float on, match:class ^(org.kde.dolphin)$, match:title ^(Progress Dialog — Dolphin)$
windowrule = float on, match:class ^(org.kde.dolphin)$, match:title ^(Copying — Dolphin)$
windowrule = float on, match:title ^(About Mozilla Firefox)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Library)$
windowrule = float on, match:class ^(kvantummanager)$
windowrule = float on, match:class ^(qt5ct)$
windowrule = float on, match:class ^(qt6ct)$
windowrule = float on, match:class ^(org.kde.ark)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-applet)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$


windowrule = float on, size 440 390, move ((monitor_w*1)-456) (30), no_anim on, match:class ^(org.kde.plasmawindowed)$

windowrule = no_anim on, match:class ^(ulauncher)$

# Fix flameshot
# from: https://ryanwise.me/blog/flameshot-on-hyprland/

windowrule = move (0) (0), pin on, fullscreen_state on, float on, match:class (flameshot), match:title (flameshot)

# Clipse
# from: https://wiki.hyprland.org/Useful-Utilities/Clipboard-Managers/

windowrule = float on, size 622 652, stay_focused on, match:class ^(clipse)$

